export const languages: Record<string, string> = {
  en: 'English',
  id: 'Bahasa Indonesia',
  vi: 'Tiếng Việt',
  cs: 'Čeština',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  it: 'Italiano',
  hu: 'Magyar',
  ms: 'Bahasa Melayu',
  nl: 'Nederlands',
  pl: 'Polski',
  pt: 'Português',
  th: 'ไทย',
  tr: 'Türkçe',
  el: 'Ελληνικά',
  ru: 'Русский',
  ar: 'العربية',
  ko: '한국어',
  ja: '日本語',
  ro: 'Română',
  bn: 'বাংলা',
  ur: 'اردو',
  hi: 'हिन्दी',
};

export const languagesArray = [
  { value: 'en', label: 'English' },
  { value: 'id', label: 'Bahasa Indonesia' },
  { value: 'vi', label: 'Tiếng Việt' },
  { value: 'cs', label: 'Čeština' },
  { value: 'es', label: 'Español' },
  { value: 'fr', label: 'Français' },
  { value: 'de', label: 'Deutsch' },
  { value: 'it', label: 'Italiano' },
  { value: 'hu', label: 'Magyar' },
  { value: 'ms', label: 'Bahasa Melayu' },
  { value: 'nl', label: 'Nederlands' },
  { value: 'pl', label: 'Polski' },
  { value: 'pt', label: 'Português' },
  { value: 'th', label: 'ไทย' },
  { value: 'tr', label: 'Türkçe' },
  { value: 'el', label: 'Ελληνικά' },
  { value: 'ru', label: 'Русский' },
  { value: 'ar', label: 'العربية' },
  { value: 'ko', label: '한국어' },
  { value: 'ja', label: '日本語' },
  { value: 'ro', label: 'Română' },
  { value: 'bn', label: 'বাংলা' },
  { value: 'ur', label: 'اردو' },
  { value: 'hi', label: 'हिन्दी' },
];
