export const languages: Record<string, string> = {
  en: 'English',
  id: 'Bahasa Indonesia',
  vi: 'Tiếng Việt',
  cs: 'Čeština',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  it: 'Italiano',
  hu: 'Magyar',
  ms: 'Bahasa Melayu',
  nl: 'Nederlands',
  pl: 'Polski',
  pt: 'Português',
  th: 'ไทย',
  tr: 'Türkçe',
  el: 'Ελληνικά',
  ru: 'Русский',
  ar: 'العربية',
  ko: '한국어',
  ja: '日本語',
  ro: 'Română',
  bn: 'বাংলা',
  ur: 'اردو',
  hi: 'हिन्दी',
};
